### ISSUE TITLE
A Bit Confused 

### ISSUE THREAD

**Issue by DJ-Dingleberry** [uditkarode/epsilon#1]
Is this kernel for oss vendor or for miui vendor custom roms?

**Comment by uditkarode** [comment]
It works on both, there's two versions, a regular one and one with `_MIUI` appended

the _MIUI version is for ROMS that use a panel dimension multiplier of 0.1, which seems to be what MIUI vendor based ROMs do by default

Arrow also seems to be setting it to 0.1, so use _MIUI version for Arrow and MIUI vendor based ROMs

(There's only the _MIUI version on github releases, check @sweet_epsilon on Telegram for the regular build)

**Comment by DJ-Dingleberry** [comment]
Thanks for the detailed info and thanks for this awesome kernel.
