### ISSUE TITLE
how to build this?

### ISSUE THREAD

**Issue by cmm** [uditkarode/epsilon#3]
(not an issue but rather a question)

hi!
what process do you use to build and package this kernel?
a link would suffice, if a generic guide for building flashable kernels like this exists anywhere (my google-fu is failing me).

**Comment by uditkarode** [comment]
* clone the `master` branch
* take the directory `flasher` from the branch `11` and put it where you cloned the `master` branch
* go into the folder where you cloned the `master` branch
* run `kernel_setup.sh`

that should build and put the flashable zip in the flasher directory when it's done :)
